### ISSUE TITLE
vtree$.flatMapLatest is not a function 

### ISSUE THREAD

**Issue by HughGrant** [cyclejs/rxjs-run#3]
RxJS uses `switchMap` instead of `flatMapLatest`

don't know why still get this error when using `rxjs-run`, isn't it suppose to handle this?

**Comment by TylorS** [comment]
Cycle Diversity doesn't do any sort of magic like that, it simply allows you to use the stream library you would like to. If you're using Rxjs 5 you will only have access to the methods that Rxjs 5 offers. Like switchMap instead of flatMapLatest.

**Comment by HughGrant** [comment]
OK, thanks for your explanation.

So the error comes from `@cycle/dom`. Is this mean that `@cycle/dom` is not RxJS5 ready?

@TylorS

**Comment by TylorS** [comment]
@cycle/dom is written using xstream, but is written to be able to do conversions to/from other stream libraries. For instance, its tests are even written in RxJS 5.
